### ISSUE TITLE
Not being able to reproduce reported results.

### ISSUE THREAD

**Issue by ajoshi944** [HubYZ/LatentEnhancement#1]
Hello,

I followed the instructions to extract the TV decomposition and obtain the enhanced images on NIST-SD 27. I am using the parameters mentioned in the article. However, I cannot get the same image quality or CMC curves as reported in the paper.

Are there any additional steps to get the results as reported in the paper? I would appreciate any help. 

Thank you,
Amol

**Comment by HubYZ** [comment]
when you calculate the matching scores using Verifinger, you need to change the default matching threshold. Otherwise, lots of matching scores will be 0.

**Comment by ajoshi944** [comment]
Thanks for your response. Changing the threshold helps in reducing 0 matching scores. But what method was used for ROI mask generation? Should the latents be masked or just the enhanced latents?

**Comment by HubYZ** [comment]
Please refer to the paper about how to get the mask and how to use the mask.
